---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: falcorules.falco.gardener.cloud
spec:
  group: falco.gardener.cloud
  scope: Cluster
  names:
    plural: falcorules
    singular: falcorule
    kind: FalcoRule
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        required:
        - spec
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
