//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	config "github.com/gardener/gardener-extension-shoot-falco-service/pkg/apis/config"
	apisconfig "github.com/gardener/gardener/extensions/pkg/apis/config"
	configv1alpha1 "github.com/gardener/gardener/extensions/pkg/apis/config/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Configuration)(nil), (*config.Configuration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Configuration_To_config_Configuration(a.(*Configuration), b.(*config.Configuration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.Configuration)(nil), (*Configuration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_Configuration_To_v1alpha1_Configuration(a.(*config.Configuration), b.(*Configuration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Falco)(nil), (*config.Falco)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Falco_To_config_Falco(a.(*Falco), b.(*config.Falco), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.Falco)(nil), (*Falco)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_Falco_To_v1alpha1_Falco(a.(*config.Falco), b.(*Falco), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Version)(nil), (*config.Version)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Version_To_config_Version(a.(*Version), b.(*config.Version), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.Version)(nil), (*Version)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_Version_To_v1alpha1_Version(a.(*config.Version), b.(*Version), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_Configuration_To_config_Configuration(in *Configuration, out *config.Configuration, s conversion.Scope) error {
	out.Falco = (*config.Falco)(unsafe.Pointer(in.Falco))
	out.HealthCheckConfig = (*apisconfig.HealthCheckConfig)(unsafe.Pointer(in.HealthCheckConfig))
	return nil
}

// Convert_v1alpha1_Configuration_To_config_Configuration is an autogenerated conversion function.
func Convert_v1alpha1_Configuration_To_config_Configuration(in *Configuration, out *config.Configuration, s conversion.Scope) error {
	return autoConvert_v1alpha1_Configuration_To_config_Configuration(in, out, s)
}

func autoConvert_config_Configuration_To_v1alpha1_Configuration(in *config.Configuration, out *Configuration, s conversion.Scope) error {
	out.Falco = (*Falco)(unsafe.Pointer(in.Falco))
	out.HealthCheckConfig = (*configv1alpha1.HealthCheckConfig)(unsafe.Pointer(in.HealthCheckConfig))
	return nil
}

// Convert_config_Configuration_To_v1alpha1_Configuration is an autogenerated conversion function.
func Convert_config_Configuration_To_v1alpha1_Configuration(in *config.Configuration, out *Configuration, s conversion.Scope) error {
	return autoConvert_config_Configuration_To_v1alpha1_Configuration(in, out, s)
}

func autoConvert_v1alpha1_Falco_To_config_Falco(in *Falco, out *config.Falco, s conversion.Scope) error {
	out.PriorityClassName = (*string)(unsafe.Pointer(in.PriorityClassName))
	out.CertificateLifetime = (*v1.Duration)(unsafe.Pointer(in.CertificateLifetime))
	out.CertificateRenewAfter = (*v1.Duration)(unsafe.Pointer(in.CertificateRenewAfter))
	out.TokenLifetime = (*v1.Duration)(unsafe.Pointer(in.TokenLifetime))
	out.TokenIssuerPrivateKey = in.TokenIssuerPrivateKey
	out.IngestorURL = in.IngestorURL
	return nil
}

// Convert_v1alpha1_Falco_To_config_Falco is an autogenerated conversion function.
func Convert_v1alpha1_Falco_To_config_Falco(in *Falco, out *config.Falco, s conversion.Scope) error {
	return autoConvert_v1alpha1_Falco_To_config_Falco(in, out, s)
}

func autoConvert_config_Falco_To_v1alpha1_Falco(in *config.Falco, out *Falco, s conversion.Scope) error {
	out.PriorityClassName = (*string)(unsafe.Pointer(in.PriorityClassName))
	out.CertificateLifetime = (*v1.Duration)(unsafe.Pointer(in.CertificateLifetime))
	out.CertificateRenewAfter = (*v1.Duration)(unsafe.Pointer(in.CertificateRenewAfter))
	out.TokenLifetime = (*v1.Duration)(unsafe.Pointer(in.TokenLifetime))
	out.TokenIssuerPrivateKey = in.TokenIssuerPrivateKey
	out.IngestorURL = in.IngestorURL
	return nil
}

// Convert_config_Falco_To_v1alpha1_Falco is an autogenerated conversion function.
func Convert_config_Falco_To_v1alpha1_Falco(in *config.Falco, out *Falco, s conversion.Scope) error {
	return autoConvert_config_Falco_To_v1alpha1_Falco(in, out, s)
}

func autoConvert_v1alpha1_Version_To_config_Version(in *Version, out *config.Version, s conversion.Scope) error {
	out.Version = in.Version
	out.Classification = in.Classification
	out.ExpiryDate = (*v1.Time)(unsafe.Pointer(in.ExpiryDate))
	return nil
}

// Convert_v1alpha1_Version_To_config_Version is an autogenerated conversion function.
func Convert_v1alpha1_Version_To_config_Version(in *Version, out *config.Version, s conversion.Scope) error {
	return autoConvert_v1alpha1_Version_To_config_Version(in, out, s)
}

func autoConvert_config_Version_To_v1alpha1_Version(in *config.Version, out *Version, s conversion.Scope) error {
	out.Version = in.Version
	out.Classification = in.Classification
	out.ExpiryDate = (*v1.Time)(unsafe.Pointer(in.ExpiryDate))
	return nil
}

// Convert_config_Version_To_v1alpha1_Version is an autogenerated conversion function.
func Convert_config_Version_To_v1alpha1_Version(in *config.Version, out *Version, s conversion.Scope) error {
	return autoConvert_config_Version_To_v1alpha1_Version(in, out, s)
}
