//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	config "github.com/gardener/gardener-extension-shoot-falco-service/pkg/apis/config"
	configv1alpha1 "github.com/gardener/gardener/extensions/pkg/apis/config/v1alpha1"
	corev1 "github.com/gardener/gardener/pkg/apis/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*AdditionalConfig)(nil), (*config.AdditionalConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AdditionalConfig_To_config_AdditionalConfig(a.(*AdditionalConfig), b.(*config.AdditionalConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.AdditionalConfig)(nil), (*AdditionalConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_AdditionalConfig_To_v1alpha1_AdditionalConfig(a.(*config.AdditionalConfig), b.(*AdditionalConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AdditionalSeedManagedResource)(nil), (*config.AdditionalSeedManagedResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AdditionalSeedManagedResource_To_config_AdditionalSeedManagedResource(a.(*AdditionalSeedManagedResource), b.(*config.AdditionalSeedManagedResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.AdditionalSeedManagedResource)(nil), (*AdditionalSeedManagedResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_AdditionalSeedManagedResource_To_v1alpha1_AdditionalSeedManagedResource(a.(*config.AdditionalSeedManagedResource), b.(*AdditionalSeedManagedResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CentralStorageConfig)(nil), (*config.CentralStorageConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CentralStorageConfig_To_config_CentralStorageConfig(a.(*CentralStorageConfig), b.(*config.CentralStorageConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.CentralStorageConfig)(nil), (*CentralStorageConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_CentralStorageConfig_To_v1alpha1_CentralStorageConfig(a.(*config.CentralStorageConfig), b.(*CentralStorageConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterIdentityTokenConfig)(nil), (*config.ClusterIdentityTokenConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterIdentityTokenConfig_To_config_ClusterIdentityTokenConfig(a.(*ClusterIdentityTokenConfig), b.(*config.ClusterIdentityTokenConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ClusterIdentityTokenConfig)(nil), (*ClusterIdentityTokenConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ClusterIdentityTokenConfig_To_v1alpha1_ClusterIdentityTokenConfig(a.(*config.ClusterIdentityTokenConfig), b.(*ClusterIdentityTokenConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Configuration)(nil), (*config.Configuration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Configuration_To_config_Configuration(a.(*Configuration), b.(*config.Configuration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.Configuration)(nil), (*Configuration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_Configuration_To_v1alpha1_Configuration(a.(*config.Configuration), b.(*Configuration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Falco)(nil), (*config.Falco)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Falco_To_config_Falco(a.(*Falco), b.(*config.Falco), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.Falco)(nil), (*Falco)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_Falco_To_v1alpha1_Falco(a.(*config.Falco), b.(*Falco), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FalcoResourceValues)(nil), (*config.FalcoResourceValues)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FalcoResourceValues_To_config_FalcoResourceValues(a.(*FalcoResourceValues), b.(*config.FalcoResourceValues), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.FalcoResourceValues)(nil), (*FalcoResourceValues)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_FalcoResourceValues_To_v1alpha1_FalcoResourceValues(a.(*config.FalcoResourceValues), b.(*FalcoResourceValues), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FalcoVPAConfig)(nil), (*config.FalcoVPAConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FalcoVPAConfig_To_config_FalcoVPAConfig(a.(*FalcoVPAConfig), b.(*config.FalcoVPAConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.FalcoVPAConfig)(nil), (*FalcoVPAConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_FalcoVPAConfig_To_v1alpha1_FalcoVPAConfig(a.(*config.FalcoVPAConfig), b.(*FalcoVPAConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FalcoVPAResources)(nil), (*config.FalcoVPAResources)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FalcoVPAResources_To_config_FalcoVPAResources(a.(*FalcoVPAResources), b.(*config.FalcoVPAResources), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.FalcoVPAResources)(nil), (*FalcoVPAResources)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_FalcoVPAResources_To_v1alpha1_FalcoVPAResources(a.(*config.FalcoVPAResources), b.(*FalcoVPAResources), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FalcosidekickOutput)(nil), (*config.FalcosidekickOutput)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FalcosidekickOutput_To_config_FalcosidekickOutput(a.(*FalcosidekickOutput), b.(*config.FalcosidekickOutput), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.FalcosidekickOutput)(nil), (*FalcosidekickOutput)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_FalcosidekickOutput_To_v1alpha1_FalcosidekickOutput(a.(*config.FalcosidekickOutput), b.(*FalcosidekickOutput), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GlobalDefaultDestination)(nil), (*config.GlobalDefaultDestination)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_GlobalDefaultDestination_To_config_GlobalDefaultDestination(a.(*GlobalDefaultDestination), b.(*config.GlobalDefaultDestination), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.GlobalDefaultDestination)(nil), (*GlobalDefaultDestination)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_GlobalDefaultDestination_To_v1alpha1_GlobalDefaultDestination(a.(*config.GlobalDefaultDestination), b.(*GlobalDefaultDestination), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HelmConfig)(nil), (*config.HelmConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_HelmConfig_To_config_HelmConfig(a.(*HelmConfig), b.(*config.HelmConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.HelmConfig)(nil), (*HelmConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_HelmConfig_To_v1alpha1_HelmConfig(a.(*config.HelmConfig), b.(*HelmConfig), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_AdditionalConfig_To_config_AdditionalConfig(in *AdditionalConfig, out *config.AdditionalConfig, s conversion.Scope) error {
	out.SeedManagedResources = *(*[]config.AdditionalSeedManagedResource)(unsafe.Pointer(&in.SeedManagedResources))
	return nil
}

// Convert_v1alpha1_AdditionalConfig_To_config_AdditionalConfig is an autogenerated conversion function.
func Convert_v1alpha1_AdditionalConfig_To_config_AdditionalConfig(in *AdditionalConfig, out *config.AdditionalConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_AdditionalConfig_To_config_AdditionalConfig(in, out, s)
}

func autoConvert_config_AdditionalConfig_To_v1alpha1_AdditionalConfig(in *config.AdditionalConfig, out *AdditionalConfig, s conversion.Scope) error {
	out.SeedManagedResources = *(*[]AdditionalSeedManagedResource)(unsafe.Pointer(&in.SeedManagedResources))
	return nil
}

// Convert_config_AdditionalConfig_To_v1alpha1_AdditionalConfig is an autogenerated conversion function.
func Convert_config_AdditionalConfig_To_v1alpha1_AdditionalConfig(in *config.AdditionalConfig, out *AdditionalConfig, s conversion.Scope) error {
	return autoConvert_config_AdditionalConfig_To_v1alpha1_AdditionalConfig(in, out, s)
}

func autoConvert_v1alpha1_AdditionalSeedManagedResource_To_config_AdditionalSeedManagedResource(in *AdditionalSeedManagedResource, out *config.AdditionalSeedManagedResource, s conversion.Scope) error {
	out.Name = in.Name
	if err := Convert_v1alpha1_HelmConfig_To_config_HelmConfig(&in.Helm, &out.Helm, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_AdditionalSeedManagedResource_To_config_AdditionalSeedManagedResource is an autogenerated conversion function.
func Convert_v1alpha1_AdditionalSeedManagedResource_To_config_AdditionalSeedManagedResource(in *AdditionalSeedManagedResource, out *config.AdditionalSeedManagedResource, s conversion.Scope) error {
	return autoConvert_v1alpha1_AdditionalSeedManagedResource_To_config_AdditionalSeedManagedResource(in, out, s)
}

func autoConvert_config_AdditionalSeedManagedResource_To_v1alpha1_AdditionalSeedManagedResource(in *config.AdditionalSeedManagedResource, out *AdditionalSeedManagedResource, s conversion.Scope) error {
	out.Name = in.Name
	if err := Convert_config_HelmConfig_To_v1alpha1_HelmConfig(&in.Helm, &out.Helm, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_AdditionalSeedManagedResource_To_v1alpha1_AdditionalSeedManagedResource is an autogenerated conversion function.
func Convert_config_AdditionalSeedManagedResource_To_v1alpha1_AdditionalSeedManagedResource(in *config.AdditionalSeedManagedResource, out *AdditionalSeedManagedResource, s conversion.Scope) error {
	return autoConvert_config_AdditionalSeedManagedResource_To_v1alpha1_AdditionalSeedManagedResource(in, out, s)
}

func autoConvert_v1alpha1_CentralStorageConfig_To_config_CentralStorageConfig(in *CentralStorageConfig, out *config.CentralStorageConfig, s conversion.Scope) error {
	out.TokenLifetime = (*v1.Duration)(unsafe.Pointer(in.TokenLifetime))
	out.TokenIssuerPrivateKey = in.TokenIssuerPrivateKey
	out.URL = in.URL
	out.Enabled = in.Enabled
	return nil
}

// Convert_v1alpha1_CentralStorageConfig_To_config_CentralStorageConfig is an autogenerated conversion function.
func Convert_v1alpha1_CentralStorageConfig_To_config_CentralStorageConfig(in *CentralStorageConfig, out *config.CentralStorageConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_CentralStorageConfig_To_config_CentralStorageConfig(in, out, s)
}

func autoConvert_config_CentralStorageConfig_To_v1alpha1_CentralStorageConfig(in *config.CentralStorageConfig, out *CentralStorageConfig, s conversion.Scope) error {
	out.TokenLifetime = (*v1.Duration)(unsafe.Pointer(in.TokenLifetime))
	out.TokenIssuerPrivateKey = in.TokenIssuerPrivateKey
	out.URL = in.URL
	out.Enabled = in.Enabled
	return nil
}

// Convert_config_CentralStorageConfig_To_v1alpha1_CentralStorageConfig is an autogenerated conversion function.
func Convert_config_CentralStorageConfig_To_v1alpha1_CentralStorageConfig(in *config.CentralStorageConfig, out *CentralStorageConfig, s conversion.Scope) error {
	return autoConvert_config_CentralStorageConfig_To_v1alpha1_CentralStorageConfig(in, out, s)
}

func autoConvert_v1alpha1_ClusterIdentityTokenConfig_To_config_ClusterIdentityTokenConfig(in *ClusterIdentityTokenConfig, out *config.ClusterIdentityTokenConfig, s conversion.Scope) error {
	out.TokenIssuerPrivateKey = in.TokenIssuerPrivateKey
	out.TokenLifetime = (*v1.Duration)(unsafe.Pointer(in.TokenLifetime))
	return nil
}

// Convert_v1alpha1_ClusterIdentityTokenConfig_To_config_ClusterIdentityTokenConfig is an autogenerated conversion function.
func Convert_v1alpha1_ClusterIdentityTokenConfig_To_config_ClusterIdentityTokenConfig(in *ClusterIdentityTokenConfig, out *config.ClusterIdentityTokenConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterIdentityTokenConfig_To_config_ClusterIdentityTokenConfig(in, out, s)
}

func autoConvert_config_ClusterIdentityTokenConfig_To_v1alpha1_ClusterIdentityTokenConfig(in *config.ClusterIdentityTokenConfig, out *ClusterIdentityTokenConfig, s conversion.Scope) error {
	out.TokenIssuerPrivateKey = in.TokenIssuerPrivateKey
	out.TokenLifetime = (*v1.Duration)(unsafe.Pointer(in.TokenLifetime))
	return nil
}

// Convert_config_ClusterIdentityTokenConfig_To_v1alpha1_ClusterIdentityTokenConfig is an autogenerated conversion function.
func Convert_config_ClusterIdentityTokenConfig_To_v1alpha1_ClusterIdentityTokenConfig(in *config.ClusterIdentityTokenConfig, out *ClusterIdentityTokenConfig, s conversion.Scope) error {
	return autoConvert_config_ClusterIdentityTokenConfig_To_v1alpha1_ClusterIdentityTokenConfig(in, out, s)
}

func autoConvert_v1alpha1_Configuration_To_config_Configuration(in *Configuration, out *config.Configuration, s conversion.Scope) error {
	out.Falco = (*config.Falco)(unsafe.Pointer(in.Falco))
	out.HealthCheckConfig = (*configv1alpha1.HealthCheckConfig)(unsafe.Pointer(in.HealthCheckConfig))
	return nil
}

// Convert_v1alpha1_Configuration_To_config_Configuration is an autogenerated conversion function.
func Convert_v1alpha1_Configuration_To_config_Configuration(in *Configuration, out *config.Configuration, s conversion.Scope) error {
	return autoConvert_v1alpha1_Configuration_To_config_Configuration(in, out, s)
}

func autoConvert_config_Configuration_To_v1alpha1_Configuration(in *config.Configuration, out *Configuration, s conversion.Scope) error {
	out.Falco = (*Falco)(unsafe.Pointer(in.Falco))
	out.HealthCheckConfig = (*configv1alpha1.HealthCheckConfig)(unsafe.Pointer(in.HealthCheckConfig))
	return nil
}

// Convert_config_Configuration_To_v1alpha1_Configuration is an autogenerated conversion function.
func Convert_config_Configuration_To_v1alpha1_Configuration(in *config.Configuration, out *Configuration, s conversion.Scope) error {
	return autoConvert_config_Configuration_To_v1alpha1_Configuration(in, out, s)
}

func autoConvert_v1alpha1_Falco_To_config_Falco(in *Falco, out *config.Falco, s conversion.Scope) error {
	out.PriorityClassName = (*string)(unsafe.Pointer(in.PriorityClassName))
	out.CentralStorage = (*config.CentralStorageConfig)(unsafe.Pointer(in.CentralStorage))
	out.ClusterIdentityToken = (*config.ClusterIdentityTokenConfig)(unsafe.Pointer(in.ClusterIdentityToken))
	out.CertificateLifetime = (*v1.Duration)(unsafe.Pointer(in.CertificateLifetime))
	out.CertificateRenewAfter = (*v1.Duration)(unsafe.Pointer(in.CertificateRenewAfter))
	out.DefaultEventDestination = (*string)(unsafe.Pointer(in.DefaultEventDestination))
	out.GlobalDefaultDestinations = *(*[]config.GlobalDefaultDestination)(unsafe.Pointer(&in.GlobalDefaultDestinations))
	out.Additional = (*config.AdditionalConfig)(unsafe.Pointer(in.Additional))
	out.FalcoVPA = (*config.FalcoVPAConfig)(unsafe.Pointer(in.FalcoVPA))
	out.DefaultRequests = (*config.FalcoResourceValues)(unsafe.Pointer(in.DefaultRequests))
	out.DefaultLimits = (*config.FalcoResourceValues)(unsafe.Pointer(in.DefaultLimits))
	return nil
}

// Convert_v1alpha1_Falco_To_config_Falco is an autogenerated conversion function.
func Convert_v1alpha1_Falco_To_config_Falco(in *Falco, out *config.Falco, s conversion.Scope) error {
	return autoConvert_v1alpha1_Falco_To_config_Falco(in, out, s)
}

func autoConvert_config_Falco_To_v1alpha1_Falco(in *config.Falco, out *Falco, s conversion.Scope) error {
	out.PriorityClassName = (*string)(unsafe.Pointer(in.PriorityClassName))
	out.CentralStorage = (*CentralStorageConfig)(unsafe.Pointer(in.CentralStorage))
	out.ClusterIdentityToken = (*ClusterIdentityTokenConfig)(unsafe.Pointer(in.ClusterIdentityToken))
	out.CertificateLifetime = (*v1.Duration)(unsafe.Pointer(in.CertificateLifetime))
	out.CertificateRenewAfter = (*v1.Duration)(unsafe.Pointer(in.CertificateRenewAfter))
	out.DefaultEventDestination = (*string)(unsafe.Pointer(in.DefaultEventDestination))
	out.GlobalDefaultDestinations = *(*[]GlobalDefaultDestination)(unsafe.Pointer(&in.GlobalDefaultDestinations))
	out.Additional = (*AdditionalConfig)(unsafe.Pointer(in.Additional))
	out.FalcoVPA = (*FalcoVPAConfig)(unsafe.Pointer(in.FalcoVPA))
	out.DefaultRequests = (*FalcoResourceValues)(unsafe.Pointer(in.DefaultRequests))
	out.DefaultLimits = (*FalcoResourceValues)(unsafe.Pointer(in.DefaultLimits))
	return nil
}

// Convert_config_Falco_To_v1alpha1_Falco is an autogenerated conversion function.
func Convert_config_Falco_To_v1alpha1_Falco(in *config.Falco, out *Falco, s conversion.Scope) error {
	return autoConvert_config_Falco_To_v1alpha1_Falco(in, out, s)
}

func autoConvert_v1alpha1_FalcoResourceValues_To_config_FalcoResourceValues(in *FalcoResourceValues, out *config.FalcoResourceValues, s conversion.Scope) error {
	out.Memory = in.Memory
	out.Cpu = in.Cpu
	return nil
}

// Convert_v1alpha1_FalcoResourceValues_To_config_FalcoResourceValues is an autogenerated conversion function.
func Convert_v1alpha1_FalcoResourceValues_To_config_FalcoResourceValues(in *FalcoResourceValues, out *config.FalcoResourceValues, s conversion.Scope) error {
	return autoConvert_v1alpha1_FalcoResourceValues_To_config_FalcoResourceValues(in, out, s)
}

func autoConvert_config_FalcoResourceValues_To_v1alpha1_FalcoResourceValues(in *config.FalcoResourceValues, out *FalcoResourceValues, s conversion.Scope) error {
	out.Memory = in.Memory
	out.Cpu = in.Cpu
	return nil
}

// Convert_config_FalcoResourceValues_To_v1alpha1_FalcoResourceValues is an autogenerated conversion function.
func Convert_config_FalcoResourceValues_To_v1alpha1_FalcoResourceValues(in *config.FalcoResourceValues, out *FalcoResourceValues, s conversion.Scope) error {
	return autoConvert_config_FalcoResourceValues_To_v1alpha1_FalcoResourceValues(in, out, s)
}

func autoConvert_v1alpha1_FalcoVPAConfig_To_config_FalcoVPAConfig(in *FalcoVPAConfig, out *config.FalcoVPAConfig, s conversion.Scope) error {
	if err := Convert_v1alpha1_FalcoVPAResources_To_config_FalcoVPAResources(&in.MinAllowed, &out.MinAllowed, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_FalcoVPAResources_To_config_FalcoVPAResources(&in.MaxAllowed, &out.MaxAllowed, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_FalcoVPAConfig_To_config_FalcoVPAConfig is an autogenerated conversion function.
func Convert_v1alpha1_FalcoVPAConfig_To_config_FalcoVPAConfig(in *FalcoVPAConfig, out *config.FalcoVPAConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_FalcoVPAConfig_To_config_FalcoVPAConfig(in, out, s)
}

func autoConvert_config_FalcoVPAConfig_To_v1alpha1_FalcoVPAConfig(in *config.FalcoVPAConfig, out *FalcoVPAConfig, s conversion.Scope) error {
	if err := Convert_config_FalcoVPAResources_To_v1alpha1_FalcoVPAResources(&in.MinAllowed, &out.MinAllowed, s); err != nil {
		return err
	}
	if err := Convert_config_FalcoVPAResources_To_v1alpha1_FalcoVPAResources(&in.MaxAllowed, &out.MaxAllowed, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_FalcoVPAConfig_To_v1alpha1_FalcoVPAConfig is an autogenerated conversion function.
func Convert_config_FalcoVPAConfig_To_v1alpha1_FalcoVPAConfig(in *config.FalcoVPAConfig, out *FalcoVPAConfig, s conversion.Scope) error {
	return autoConvert_config_FalcoVPAConfig_To_v1alpha1_FalcoVPAConfig(in, out, s)
}

func autoConvert_v1alpha1_FalcoVPAResources_To_config_FalcoVPAResources(in *FalcoVPAResources, out *config.FalcoVPAResources, s conversion.Scope) error {
	out.Memory = in.Memory
	out.Cpu = in.Cpu
	return nil
}

// Convert_v1alpha1_FalcoVPAResources_To_config_FalcoVPAResources is an autogenerated conversion function.
func Convert_v1alpha1_FalcoVPAResources_To_config_FalcoVPAResources(in *FalcoVPAResources, out *config.FalcoVPAResources, s conversion.Scope) error {
	return autoConvert_v1alpha1_FalcoVPAResources_To_config_FalcoVPAResources(in, out, s)
}

func autoConvert_config_FalcoVPAResources_To_v1alpha1_FalcoVPAResources(in *config.FalcoVPAResources, out *FalcoVPAResources, s conversion.Scope) error {
	out.Memory = in.Memory
	out.Cpu = in.Cpu
	return nil
}

// Convert_config_FalcoVPAResources_To_v1alpha1_FalcoVPAResources is an autogenerated conversion function.
func Convert_config_FalcoVPAResources_To_v1alpha1_FalcoVPAResources(in *config.FalcoVPAResources, out *FalcoVPAResources, s conversion.Scope) error {
	return autoConvert_config_FalcoVPAResources_To_v1alpha1_FalcoVPAResources(in, out, s)
}

func autoConvert_v1alpha1_FalcosidekickOutput_To_config_FalcosidekickOutput(in *FalcosidekickOutput, out *config.FalcosidekickOutput, s conversion.Scope) error {
	out.Key = in.Key
	out.Value = (*runtime.RawExtension)(unsafe.Pointer(in.Value))
	return nil
}

// Convert_v1alpha1_FalcosidekickOutput_To_config_FalcosidekickOutput is an autogenerated conversion function.
func Convert_v1alpha1_FalcosidekickOutput_To_config_FalcosidekickOutput(in *FalcosidekickOutput, out *config.FalcosidekickOutput, s conversion.Scope) error {
	return autoConvert_v1alpha1_FalcosidekickOutput_To_config_FalcosidekickOutput(in, out, s)
}

func autoConvert_config_FalcosidekickOutput_To_v1alpha1_FalcosidekickOutput(in *config.FalcosidekickOutput, out *FalcosidekickOutput, s conversion.Scope) error {
	out.Key = in.Key
	out.Value = (*runtime.RawExtension)(unsafe.Pointer(in.Value))
	return nil
}

// Convert_config_FalcosidekickOutput_To_v1alpha1_FalcosidekickOutput is an autogenerated conversion function.
func Convert_config_FalcosidekickOutput_To_v1alpha1_FalcosidekickOutput(in *config.FalcosidekickOutput, out *FalcosidekickOutput, s conversion.Scope) error {
	return autoConvert_config_FalcosidekickOutput_To_v1alpha1_FalcosidekickOutput(in, out, s)
}

func autoConvert_v1alpha1_GlobalDefaultDestination_To_config_GlobalDefaultDestination(in *GlobalDefaultDestination, out *config.GlobalDefaultDestination, s conversion.Scope) error {
	out.Name = in.Name
	if err := Convert_v1alpha1_FalcosidekickOutput_To_config_FalcosidekickOutput(&in.FalcosidekickOutput, &out.FalcosidekickOutput, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_GlobalDefaultDestination_To_config_GlobalDefaultDestination is an autogenerated conversion function.
func Convert_v1alpha1_GlobalDefaultDestination_To_config_GlobalDefaultDestination(in *GlobalDefaultDestination, out *config.GlobalDefaultDestination, s conversion.Scope) error {
	return autoConvert_v1alpha1_GlobalDefaultDestination_To_config_GlobalDefaultDestination(in, out, s)
}

func autoConvert_config_GlobalDefaultDestination_To_v1alpha1_GlobalDefaultDestination(in *config.GlobalDefaultDestination, out *GlobalDefaultDestination, s conversion.Scope) error {
	out.Name = in.Name
	if err := Convert_config_FalcosidekickOutput_To_v1alpha1_FalcosidekickOutput(&in.FalcosidekickOutput, &out.FalcosidekickOutput, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_GlobalDefaultDestination_To_v1alpha1_GlobalDefaultDestination is an autogenerated conversion function.
func Convert_config_GlobalDefaultDestination_To_v1alpha1_GlobalDefaultDestination(in *config.GlobalDefaultDestination, out *GlobalDefaultDestination, s conversion.Scope) error {
	return autoConvert_config_GlobalDefaultDestination_To_v1alpha1_GlobalDefaultDestination(in, out, s)
}

func autoConvert_v1alpha1_HelmConfig_To_config_HelmConfig(in *HelmConfig, out *config.HelmConfig, s conversion.Scope) error {
	out.OCIRepository = (*corev1.OCIRepository)(unsafe.Pointer(in.OCIRepository))
	out.Chart = (*string)(unsafe.Pointer(in.Chart))
	out.Values = (*runtime.RawExtension)(unsafe.Pointer(in.Values))
	return nil
}

// Convert_v1alpha1_HelmConfig_To_config_HelmConfig is an autogenerated conversion function.
func Convert_v1alpha1_HelmConfig_To_config_HelmConfig(in *HelmConfig, out *config.HelmConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_HelmConfig_To_config_HelmConfig(in, out, s)
}

func autoConvert_config_HelmConfig_To_v1alpha1_HelmConfig(in *config.HelmConfig, out *HelmConfig, s conversion.Scope) error {
	out.OCIRepository = (*corev1.OCIRepository)(unsafe.Pointer(in.OCIRepository))
	out.Chart = (*string)(unsafe.Pointer(in.Chart))
	out.Values = (*runtime.RawExtension)(unsafe.Pointer(in.Values))
	return nil
}

// Convert_config_HelmConfig_To_v1alpha1_HelmConfig is an autogenerated conversion function.
func Convert_config_HelmConfig_To_v1alpha1_HelmConfig(in *config.HelmConfig, out *HelmConfig, s conversion.Scope) error {
	return autoConvert_config_HelmConfig_To_v1alpha1_HelmConfig(in, out, s)
}
