version: "2"
run:
  concurrency: 4
linters:
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
    paths:
      - "zz_generated\\..*\\.go$"
formatters:
  exclusions:
    generated: lax
    paths:
      - "zz_generated\\..*\\.go$"
