#!/usr/bin/env bash
#
# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

COMPONENT_PREFIXES="europe-docker.pkg.dev/gardener-project" \
                   "$(dirname $0)"/hack/component_descriptor "$(dirname $0)"/..