#!/bin/bash

# SPDX-FileCopyrightText: Copyright Contributors to the Gardener project
#
# SPDX-License-Identifier: Apache-2.0

set -o errexit
set -o nounset
set -o pipefail

cd "$(dirname $0)/.."

git config --global user.email "gardener@sap.com"
git config --global user.name "Gardener CI/CD"

export GOTOOLCHAIN=auto

# mot part of the CI/CD image
# make validate-falco-rules

./hack/validate-falco-rules falco/falco-profile.yaml falco/rules
