apiVersion: falco.gardener.cloud/v1alpha1
kind: FalcoProfile
metadata:
  name: falco
spec:
  images:
    falco:
    - architecture: amd64
      repository: falcosecurity/falco-distroless
      tag: 0.37.1
      version: 0.37.1
    - architecture: amd64
      repository: falcosecurity/falco-distroless
      tag: 0.38.0
      version: 0.38.0
    - architecture: amd64
      repository: falcosecurity/falco-distroless
      tag: 0.38.1
      version: 0.38.1
    - architecture: amd64
      repository: falcosecurity/falco-distroless
      tag: 0.38.2
      version: 0.38.2
    - architecture: amd64
      repository: falcosecurity/falco-distroless
      tag: 0.39.1
      version: 0.39.1
    falcoctl:
    - architecture: amd64
      repository: falcosecurity/falcoctl
      tag: 0.9.1
      version: 0.9.1
    falcosidekick:
    - architecture: amd64
      repository: falcosecurity/falcosidekick
      tag: 2.28.0
      version: 2.28.0
    - architecture: amd64
      repository: falcosecurity/falcosidekick
      tag: 2.29.0
      version: 2.29.0
  versions:
    falco:
    - classification: deprecated
      expirationDate: '2024-10-25T23:59:59Z'
      rulesVersion: 3.0.1
      version: 0.37.1
    - classification: deprecated
      expirationDate: '2024-10-25T23:59:59Z'
      rulesVersion: 3.0.1
      version: 0.38.0
    - classification: deprecated
      expirationDate: '2024-10-25T23:59:59Z'
      rulesVersion: 3.0.1
      version: 0.38.1
    - classification: deprecated
      expirationDate: '2024-10-25T23:59:59Z'
      rulesVersion: 3.0.1
      version: 0.38.2
    - classification: supported
      rulesVersion: 3.2.0
      version: 0.39.1
    falcoctl:
    - classification: supported
      version: 0.9.1
    falcosidekick:
    - classification: deprecated
      version: 2.28.0
    - classification: supported
      version: 2.29.0

