apiVersion: falco.gardener.cloud/v1alpha1
kind: FalcoProfile
metadata:
  name: falco
spec:
  images:
    falco:
    - repository: falcosecurity/falco-distroless
      tag: 0.39.1
      version: 0.39.1
    - repository: falcosecurity/falco-distroless
      tag: 0.39.2
      version: 0.39.2
    - repository: falcosecurity/falco
      tag: 0.40.0
      version: 0.40.0
    falcosidekick:
    - repository: falcosecurity/falcosidekick
      tag: 2.29.0
      version: 2.29.0
    - repository: falcosecurity/falcosidekick
      tag: 2.30.0
      version: 2.30.0
    - repository: falcosecurity/falcosidekick
      tag: 2.31.1
      version: 2.31.1
  versions:
    falco:
    - classification: deprecated
      expirationDate: '2025-04-15T23:59:59Z'
      rulesVersion: 3.2.0
      version: 0.39.1
    - classification: deprecated
      rulesVersion: 3.2.0
      version: 0.39.2
    - classification: supported
      rulesVersion: 3.2.0
      version: 0.40.0
    falcosidekick:
    - classification: deprecated
      version: 2.29.0
    - classification: supported
      version: 2.30.0
    - classification: supported
      version: 2.31.1

