apiVersion: falco.gardener.cloud/v1alpha1
kind: FalcoProfile
metadata:
  name: falco
spec:
  images:
    falco:
    - architecture: amd64
      repository: falcosecurity/falco-distroless
      tag: 0.39.1
      version: 0.39.1
    - architecture: amd64
      repository: falcosecurity/falco-distroless
      tag: 0.39.2
      version: 0.39.2
    falcoctl:
    - architecture: amd64
      repository: falcosecurity/falcoctl
      tag: 0.9.1
      version: 0.9.1
    - architecture: amd64
      repository: falcosecurity/falcoctl
      tag: 0.10.0
      version: 0.10.0
    - architecture: amd64
      repository: falcosecurity/falcoctl
      tag: '0.11'
      version: 0.11.0
    falcosidekick:
    - architecture: amd64
      repository: falcosecurity/falcosidekick
      tag: 2.29.0
      version: 2.29.0
    - architecture: amd64
      repository: falcosecurity/falcosidekick
      tag: 2.30.0
      version: 2.30.0
  versions:
    falco:
    - classification: deprecated
      rulesVersion: 3.2.0
      version: 0.39.1
    - classification: supported
      rulesVersion: 3.2.0
      version: 0.39.2
    falcoctl:
    - classification: deprecated
      version: 0.9.1
    - classification: deprecated
      version: 0.10.0
    - classification: supported
      version: 0.11.0
    falcosidekick:
    - classification: deprecated
      version: 2.29.0
    - classification: supported
      version: 2.30.0

