apiVersion: falco.gardener.cloud/v1alpha1
kind: FalcoProfile
metadata:
  name: falco
spec:
  images:
    falco:
    - architecture: amd64
      repository: falcosecurity/falco-distroless
      tag: 0.39.1
      version: 0.39.1
    - architecture: amd64
      repository: falcosecurity/falco-distroless
      tag: 0.39.2
      version: 0.39.2
    - architecture: amd64
      repository: falcosecurity/falco
      tag: 0.40.0
      version: 0.40.0
    falcoctl:
    - architecture: amd64
      repository: falcosecurity/falcoctl
      tag: 0.10.1
      version: 0.10.1
    - architecture: amd64
      repository: falcosecurity/falcoctl
      tag: '0.11'
      version: 0.11.0
    falcosidekick:
    - architecture: amd64
      repository: falcosecurity/falcosidekick
      tag: 2.29.0
      version: 2.29.0
    - architecture: amd64
      repository: falcosecurity/falcosidekick
      tag: 2.30.0
      version: 2.30.0
    - architecture: amd64
      repository: europe-docker.pkg.dev/gardener-project/releases/falcosidekick-fork
      tag: 0.34.0-dev-8839623021823f8a74d743dceae1125e317a883a
      version: 2.30.1
  versions:
    falco:
    - classification: deprecated
      expirationDate: '2025-04-15T23:59:59Z'
      rulesVersion: 3.2.0
      version: 0.39.1
    - classification: supported
      rulesVersion: 3.2.0
      version: 0.39.2
    - classification: preview
      rulesVersion: 3.2.0
      version: 0.40.0
    falcoctl:
    - classification: deprecated
      version: 0.10.1
    - classification: supported
      version: 0.11.0
    falcosidekick:
    - classification: deprecated
      version: 2.29.0
    - classification: supported
      version: 2.30.0
    - classification: supported
      version: 2.30.1

