apiVersion: falco.gardener.cloud/v1alpha1
kind: FalcoProfile
metadata:
  name: falco
spec:
  images:
    falco:
    - repository: falcosecurity/falco
      tag: 0.40.0
      version: 0.40.0
    - repository: falcosecurity/falco
      tag: 0.41.3
      version: 0.41.3
    - repository: falcosecurity/falco
      tag: 0.42.0
      version: 0.42.0
    falcosidekick:
    - repository: falcosecurity/falcosidekick
      tag: 2.30.0
      version: 2.30.0
    - repository: falcosecurity/falcosidekick
      tag: 2.31.1
      version: 2.31.1
  versions:
    falco:
    - classification: supported
      rulesVersion: 3.2.0
      version: 0.40.0
    - classification: supported
      rulesVersion: 4.0.0
      version: 0.41.3
    - classification: preview
      rulesVersion: 4.0.0
      version: 0.42.0
    falcosidekick:
    - classification: deprecated
      version: 2.30.0
    - classification: supported
      version: 2.31.1

