apiVersion: falco.gardener.cloud/v1alpha1
kind: FalcoProfile
metadata:
  name: falco
spec:
  images:
    falco:
    - architecture: amd64
      repository: falcosecurity/falco-distroless
      tag: 0.39.1
      version: 0.39.1
    - architecture: amd64
      repository: falcosecurity/falco-distroless
      tag: 0.39.2
      version: 0.39.2
    falcoctl:
    - architecture: amd64
      repository: falcosecurity/falcoctl
      tag: 0.9.1
      version: 0.9.1
    - architecture: amd64
      repository: falcosecurity/falcoctl
      tag: 0.10.0
      version: 0.10.0
    falcosidekick:
    - architecture: amd64
      repository: falcosecurity/falcosidekick
      tag: 2.29.0
      version: 2.29.0
  versions:
    falco:
    - classification: supported
      rulesVersion: 3.2.0
      version: 0.39.1
    - classification: preview
      rulesVersion: 3.2.0
      version: 0.39.2
    falcoctl:
    - classification: supported
      version: 0.9.1
    - classification: supported
      version: 0.10.0
    falcosidekick:
    - classification: supported
      version: 2.29.0

