# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: Secret
metadata:
  name: extension-shoot-falco-service-config
  namespace: {{ .Release.Namespace }}	
stringData:
  config.yaml: |
    apiVersion: falco.extensions.config.gardener.cloud/v1alpha1
    kind: Configuration
    falco:
      {{- toYaml .Values.falco | nindent 6 }}
