apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gardener-extension-falco-profiles
rules:
- apiGroups:
  - falco.gardener.cloud
  resources:
  - falcoprofiles
  verbs:
  - get
  - list
  - watch