apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gardener-extension-falco-profiles
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gardener-extension-falco-profiles
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated