---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: falcosidekick
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: falcosidekick
    helm.sh/chart: {{ include "falco.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: falcosidekick
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: falcosidekick
    helm.sh/chart: {{ include "falco.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups:
    - ""
  resources:
    - endpoints
  verbs:
    - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: falcosidekick
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: falcosidekick
    helm.sh/chart: {{ include "falco.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: falcosidekick
subjects:
- kind: ServiceAccount
  name: falcosidekick
{{- if .Values.falcosidekick.config.policyreport.enabled  }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: falcosidekick
  labels:
    app.kubernetes.io/name: falcosidekick
    helm.sh/chart: {{ include "falco.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups:
    - "wgpolicyk8s.io"
  resources:
    - policyreports
    - clusterpolicyreports
  verbs:
    - get
    - create
    - delete
    - update
- nonResourceURLs:
    - /vali/api/v1/push
  verbs:
    - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: falcosidekick
  labels:
    app.kubernetes.io/name: falcosidekick
    helm.sh/chart: {{ include "falco.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: falcosidekick
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: falcosidekick
{{- end }}
