{{- if not .Values.daemonSetOnly }}
{{- if .Values.falcoIncubatingRules }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: falco-incubating-rules
  namespace: {{ include "falco.namespace" . }}
data:
  falco-incubating_rules.yaml: |-
{{ .Values.falcoIncubatingRules | indent 4 }}
{{- end}}
{{- end }}
