{{- if .Values.customRules }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: falco-custom-rules
  namespace: {{ include "falco.namespace" . }}
  labels:
    {{- include "falco.labels" . | nindent 4 }}
data:
{{- range $rulesFile := .Values.customRules }}
  {{ $rulesFile.filename }}: |-
{{ $rulesFile.content | indent 4 }}
{{- end }}
{{- end }}