apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "falco.fullname" . }}
  namespace: {{ include "falco.namespace" . }}
  labels:
    {{- include "falco.labels" . | nindent 4 }}
data:
  falco.yaml: |-
    {{- include "falco.falcosidekickConfig" . }}
    {{- include "falco.gardenerManagedRules" . }}
    {{- toYaml .Values.falco | nindent 4 }}
