{{- if .Values.falcoRules }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: falco-rules
  namespace: {{ include "falco.namespace" . }}
data:
  falco-incubating_rules.yaml: |-
{{ .Values.falcoRules | indent 4 }}
{{- end}}