{{- if .Values.falcoSandboxRules }}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ include "falco.namespace" . }}
  name: falco-sandbox-rules
data:
  falco-sandbox_rules.yaml: |-
{{ .Values.falcoSandboxRules | indent 4 }}
{{- end }}