apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "falco.fullname" . }}
  namespace: {{ include "falco.namespace" . }}
  labels:
    {{- include "falco.labels" . | nindent 4 }}
data:
  falco.yaml: |-
    {{- include "falco.falcosidekickConfig" . }}
    {{- if eq .Values.configProvider "gardener" }}
    {{- include "falco.gardenerManagedRules" . }}
    {{- end }}
    {{- toYaml .Values.falco | nindent 4 }}
    {{- include "falco.containerPlugin" . -}}
    {{- include "k8smeta.configuration" . -}}


